version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1

    steps:
      - checkout
      - run:
          name: validate ami.json
          working_directory: ~/project
          command: packer validate ami.json
      - run:
          name: build ami
          working_directory: ~/project
          command: packer build -var 'aws_access_key=${aws_access_key}' -var 'aws_secret_key=${aws_secret_key}' -var 'aws_region=${aws_region}' ami.json
