version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1

    steps:
      - checkout
      - run:
          name: validate ami.json
          working_directory: ~/project
          command: packer validate ami.json
      - run:
          name: import variables
          command: |
            echo 'export ACCESS_KEY=$aws_access_key' >> $BASH_ENV
            echo 'export SECRET_KEY=$aws_secret_key' >> $BASH_ENV
            echo 'export REGION=$aws_region' >> $BASH_ENV
            echo 'export USERS=$aws_users' >> $BASH_ENV
            source $BASH_ENV
            echo $REGION
      - run:
          name: build ami
          working_directory: ~/project
          command: packer build -var 'aws_access_key=$ACCESS_KEY' -var 'aws_secret_key=$SECRET_KEY' -var 'aws_region=us-east-1' -var 'aws_users=$USERS' ami.json
